---
name: Cloudflared
version: dev
slug: cloudflared
description: >
  Use a Cloudflared tunnel (formerly Argo Tunnel)
  to remotely connect to Home Assistant without opening any ports
url: "https://github.com/brenner-tobias/addon-cloudflared/"
startup: services
init: false
hassio_api: true
homeassistant_api: true
hassio_role: admin
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  external_hostname: ""
  internal_ha_port: "8123"
  tunnel_name: homeassistant
  nginxproxymanager: false
schema:
  external_hostname: str
  internal_ha_port: port
  tunnel_name: str
  nginxproxymanager: bool
  reset_cloudflared_files: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
