---
name: Cloudflared
version: dev
slug: cloudflared
description: >
  Use a Cloudflared tunnel (formerly Argo Tunnel)
  to remotely connect to Home Assistant without opening any ports
url: "https://github.com/brenner-tobias/addon-cloudflared/"
init: false
hassio_api: true
hassio_role: admin
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  external_ha_hostname: "ha-test.example.com"
  tunnel_name: "homeassistant-test"
  additional_hosts:
    - hostname: "ds.example.com"
      service: "http://192.168.1.2"
    - hostname: "fritz.example.com"
      service: "http://192.168.1.1"
schema:
  external_ha_hostname: str
  tunnel_name: str
  additional_hosts:
    - hostname: str?
      service: str?
  nginxproxymanager: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reset_cloudflared_files: bool?
