---
name: Cloudflared
version: dev
slug: cloudflared
description: "Use a Cloudflared tunnel (formerly Argo Tunnel)
  to remotely connect to Home Assistant without opening any ports"
url: "https://github.com/brenner-tobias/addon-cloudflared/"
codenotary: dev@brenner.tech
init: false
hassio_api: true
hassio_role: homeassistant
watchdog: "http://[HOST]:36500/healthcheck"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl:rw
  - share:rw
  - config:rw
options:
  external_hostname: ""
  tunnel_name: "homeassistant"
  additional_hosts: []
  tunnel_token: ""
schema:
  external_hostname: str?
  tunnel_name: str?
  additional_hosts:
    - hostname: str
      service: str
      disableChunkedEncoding: bool?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  quick_tunnel: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reset_cloudflared_files: bool?
  data_folder: list(config|share|ssl)?
  custom_config: bool?
  warp_enable: bool?
  warp_routes:
    - str?
  warp_reset: bool?
  tunnel_token: str?
