---
name: Cloudflare Release
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:
jobs:
  cloudflare-release:
    name: ℹ️ Check Cloudflared Release
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.4.0
      - name: ℹ️ Gather Cloudflared latest version
        id: cloudflare_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: cloudflare/cloudflared
          excludes: "prerelease, draft"
      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.3.1
      - id: test
        run: |
          latest_version="${{ steps.cloudflare_version.outputs.release }}"
          current_version=$(jq .version "./${{ steps.information.outputs.target }}/cloudflare_version.json")
          echo ${{current_version}}
          if [ "$(printf '%s\n' "$latest_version" "$current_version" | sort -V | head -n1)" = "$latest_version" ]; then 
                  echo "Greater than or equal to ${latest_version}"
          else
                  echo "Less than ${latest_version}"
          fi