---
name: Cloudflare Release
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
jobs:
  cloudflare-release:
    name: ℹ️ Gather Cloudflared latest version
    runs-on: ubuntu-latest
    steps:
      - id: timeseries
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: cloudflare/cloudflared
          excludes: "prerelease, draft"
