---
name: Cloudflare Release
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
jobs:
  cloudflare-release:
    steps:
      - uses: joutvhu/get-release@v1
        with:
          latest: true
          # Tag name start with `v`
          pattern: '^v.*'
          # Including pre-release
          prerelease: false
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
